[versions]
ksp = "2.3.0"
kgp = "2.3.0"
coroutines = "1.8.0"
kotlinpoet = "1.14.2"
librarian = "0.2.2-SNAPSHOT-22b5cf626236be6e39cdcfa486f713b4360d87d8"
gratatouille = "0.1.3"

[libraries]
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
vespene = "net.mbonnin.vespene:vespene-lib:0.5"
buildkonfig = "com.github.gmazzo.buildconfig:plugin:5.6.2"
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kgp" }
kotlin-serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kgp" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
gradle-api = { group = "dev.gradleplugins", name = "gradle-api", version = "8.0" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.6.2" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }
librarian = { module = "com.gradleup.librarian:librarian-gradle-plugin", version.ref = "librarian" }
nmcp = { module = "com.gradleup.nmcp:nmcp", version = "1.0.2-SNAPSHOT-5374b28286b7ef04a45061946bae5eff65f33093" }
okio = "com.squareup.okio:okio:3.9.0"
cast = "net.mbonnin.cast:cast:0.0.1"
gratatouille-gradle-plugin = { module = "com.gradleup.gratatouille:gratatouille-gradle-plugin", version.ref = "gratatouille" }


[plugins]
kgp = { id = "org.jetbrains.kotlin.jvm", version.ref = "kgp" }
compat-patrouille = { id = "com.gradleup.compat.patrouille", version = "0.0.0" }